### ISSUE TITLE
rfcindex.py

### ISSUE THREAD

**Issue by gregbo** [glasgow-ipl/ietfdata#137]
There's a duplicate test in line 265.  Is it a typo?

`elif (self.doc_id == "RFC2497") or (self.doc_id == "RFC2497") or \`

Also, regarding the test in line 268 for RFC2708, as far as I can tell, U+0092 was introduced in draft-ietf-printmib-job-protomap-01 in multiple places.  In -02, it was replaced with U+0027 everywhere except section 5.0.  Somehow, that stray character became the corrupt text you identified.

**Comment by csperkins** [comment]
Thanks – line 265 is a typo and I'll remove the duplicate. Thanks for the update re RFC 2708.
