### ISSUE TITLE
RFC documents no longer have submissions

### ISSUE THREAD

**Issue by sbenthall** [glasgow-ipl/ietfdata#140]
A few months ago, the following code would report that there were multiple submissions for each of the documents queried:

```
from ietfdata.datatracker import *
from ietfdata.datatracker_ext import *
import numpy as np

dt = DataTrackerExt()

g = dt.group_from_acronym('quic')
docs = list(dt.documents(group=g, doctype=dt.document_type_from_slug("rfc")))

np.array([len(draft.submissions) for draft in docs])
```

This made it possible to collect information about the date and authors of the final draft (by looking at the submissions list, ordering it by submission_date, and pulling the author information).

Now it seems that something has changed, and RFC documents appear to, as a rule, have 0 submissions.

What was the change?
Is it documented anywhere?

How can one do the following:
 - find all the RFCs for a working group
 - get the author and date information from that RFC document (the last document in the series)

Thanks!

**Comment by csperkins** [comment]
I suspect this is due to https://github.com/ietf-tools/datatracker/releases/tag/12.0.0

Maybe try to find the documents representing the RFCs for a group, then search for related documents with target equal to those documents, relationship `became_rfc`?

**Comment by sbenthall** [comment]
Thank you!
