### ISSUE TITLE
Consider replacing Pavlova with Pydantic

### ISSUE THREAD

**Issue by csperkins** [glasgow-ipl/ietfdata#55]
[Pydantic](https://github.com/samuelcolvin/pydantic/) seems to address the same problem as Pavlova, but looks to be more flexible and better supported.

**Comment by sbenthall** [comment]
Just FYI, I had a problem in my recently pip installed ietfdata. the `pavlova` package wasn't found and I had to install it separately.

I'm not sure, but it suggests an issue with the dependency configuration

**Comment by sbenthall** [comment]
Disregard this please--i had an old version

**Comment by csperkins** [comment]
Closed by 123f68f
