### ISSUE TITLE
Unify CI and Makefile test scripts

### ISSUE THREAD

**Issue by lumisota** [glasgow-ipl/ietfdata#79]
Presently, there are two test scripts: the Makefile's `test` target, and the CI configuration's `build-and-test` job. As these are separate, it is possible that they would produce different results, making it difficult to determine if changes that pass one set of tests will also pass the other.

These should be unified, ideally around the Makefile's `test` target. Unifying these test scripts should also include ensuring that sensible, human-readable output is produced locally, while reports in the required archival format are produced by the CI build.

**Comment by csperkins** [comment]
Fixed in b895260
